In [1]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT *
        FROM FACILITIES
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)

Q10: Produce a list of facilities with a total revenue less than 1000.
The output of facility name and total revenue, sorted by revenue. Remember
that there's a different cost for guests and members!

In [2]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT * 
FROM (
    SELECT sub.facility, SUM( sub.cost ) AS total_revenue
FROM (
    SELECT Facilities.name AS facility, 
CASE WHEN Bookings.memid =0
    THEN Facilities.guestcost * Bookings.slots
    ELSE Facilities.membercost * Bookings.slots
    END AS cost
FROM Bookings
    INNER JOIN Facilities ON Bookings.facid = Facilities.facid
    INNER JOIN Members ON Bookings.memid = Members.memid
    ) AS sub
GROUP BY sub.facility
    ) AS sub2
WHERE sub2.total_revenue <1000

        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Pool Table', 270)
('Snooker Table', 240)
('Table Tennis', 180)

Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order

In [3]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
    SELECT m.surname, m.firstname, m.recommendedby AS recomender_id, r.surname AS recomender_surname, r.firstname AS recomender_firstname
FROM Members AS m
    LEFT JOIN Members AS r ON m.recommendedby = r.memid
WHERE m.recommendedby != 0
ORDER BY r.surname, r.firstname;

        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('GUEST', 'GUEST', '', None, None)
('Smith', 'Darren', '', None, None)
('Smith', 'Tracy', '', None, None)
('Rownam', 'Tim', '', None, None)
('Tracy', 'Burton', '', None, None)
('Farrell', 'Jemima', '', None, None)
('Farrell', 'David', '', None, None)
('Tupperware', 'Hyacinth', '', None, None)
('Smith', 'Darren', '', None, None)
('Sarwin', 'Ramnaresh', '15', 'Bader', 'Florence')
('Coplin', 'Joan', '16', 'Baker', 'Timothy')
('Genting', 'Matthew', '5', 'Butters', 'Gerald')
('Baker', 'Timothy', '13', 'Farrell', 'Jemima')
('Pinker', 'David', '13', 'Farrell', 'Jemima')
('Rumney', 'Henrietta', '20', 'Genting', 'Matthew')
('Jones', 'Douglas', '11', 'Jones', 'David')
('Dare', 'Nancy', '4', 'Joplette', 'Janice')
('Jones', 'David', '4', 'Joplette', 'Janice')
('Hunt', 'John', '30', 'Purview', 'Millicent')
('Boothe', 'Tim', '3', 'Rownam', 'Tim')
('Joplette', 'Janice', '1', 'Smith', 'Darren')
('Butters', 'Gerald', '1', 'Smith', 'Darren')
('Owen', 'Charles', '1', 'Smith', 'Darren')
('Smith', 'Jack', '1', 'Smith', 'Darren')
('Mackenzie', 'Anna', '1', 'Smith', 'Darren')
('Worthington-Smyth', 'Henry', '2', 'Smith', 'Tracy')
('Purview', 'Millicent', '2', 'Smith', 'Tracy')
('Crumpet', 'Erica', '2', 'Smith', 'Tracy')
('Baker', 'Anne', '9', 'Stibbons', 'Ponder')
('Bader', 'Florence', '9', 'Stibbons', 'Ponder')
('Stibbons', 'Ponder', '6', 'Tracy', 'Burton')

Q12: Find the facilities with their usage by member, but not guests

In [4]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT b.facid, COUNT( b.memid ) AS mem_usage, f.name
FROM (
    SELECT facid, memid
FROM Bookings
WHERE memid !=0
    ) AS b
    LEFT JOIN Facilities AS f ON b.facid = f.facid
GROUP BY b.facid;

        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 308, 'Tennis Court 1')
(1, 276, 'Tennis Court 2')
(2, 344, 'Badminton Court')
(3, 385, 'Table Tennis')
(4, 421, 'Massage Room 1')
(5, 27, 'Massage Room 2')
(6, 195, 'Squash Court')
(7, 421, 'Snooker Table')
(8, 783, 'Pool Table')

Q13: Find the facilities usage by month, but not guests

In [20]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        

SELECT b.months, COUNT( b.memid ) AS mem_usage
FROM (
SELECT CAST(SUBSTR(starttime, 6, 2) AS INT) AS months, memid
FROM Bookings
WHERE memid !=0
) AS b
GROUP BY b.months;


        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(7, 480)
(8, 1168)
(9, 1512)